/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WardrobeRouteImport } from './routes/wardrobe'
import { Route as SoloRouteImport } from './routes/solo'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as HowtoRouteImport } from './routes/howto'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MultiLocalRouteImport } from './routes/multi/local'
import { Route as DevUiPreviewRouteImport } from './routes/dev/ui-preview'
import { Route as DevGamePreviewRouteImport } from './routes/dev/game-preview'

const WardrobeRoute = WardrobeRouteImport.update({
  id: '/wardrobe',
  path: '/wardrobe',
  getParentRoute: () => rootRouteImport,
} as any)
const SoloRoute = SoloRouteImport.update({
  id: '/solo',
  path: '/solo',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const HowtoRoute = HowtoRouteImport.update({
  id: '/howto',
  path: '/howto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiLocalRoute = MultiLocalRouteImport.update({
  id: '/multi/local',
  path: '/multi/local',
  getParentRoute: () => rootRouteImport,
} as any)
const DevUiPreviewRoute = DevUiPreviewRouteImport.update({
  id: '/dev/ui-preview',
  path: '/dev/ui-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const DevGamePreviewRoute = DevGamePreviewRouteImport.update({
  id: '/dev/game-preview',
  path: '/dev/game-preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/howto': typeof HowtoRoute
  '/ranking': typeof RankingRoute
  '/solo': typeof SoloRoute
  '/wardrobe': typeof WardrobeRoute
  '/dev/game-preview': typeof DevGamePreviewRoute
  '/dev/ui-preview': typeof DevUiPreviewRoute
  '/multi/local': typeof MultiLocalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/howto': typeof HowtoRoute
  '/ranking': typeof RankingRoute
  '/solo': typeof SoloRoute
  '/wardrobe': typeof WardrobeRoute
  '/dev/game-preview': typeof DevGamePreviewRoute
  '/dev/ui-preview': typeof DevUiPreviewRoute
  '/multi/local': typeof MultiLocalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/howto': typeof HowtoRoute
  '/ranking': typeof RankingRoute
  '/solo': typeof SoloRoute
  '/wardrobe': typeof WardrobeRoute
  '/dev/game-preview': typeof DevGamePreviewRoute
  '/dev/ui-preview': typeof DevUiPreviewRoute
  '/multi/local': typeof MultiLocalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/howto'
    | '/ranking'
    | '/solo'
    | '/wardrobe'
    | '/dev/game-preview'
    | '/dev/ui-preview'
    | '/multi/local'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/howto'
    | '/ranking'
    | '/solo'
    | '/wardrobe'
    | '/dev/game-preview'
    | '/dev/ui-preview'
    | '/multi/local'
  id:
    | '__root__'
    | '/'
    | '/howto'
    | '/ranking'
    | '/solo'
    | '/wardrobe'
    | '/dev/game-preview'
    | '/dev/ui-preview'
    | '/multi/local'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HowtoRoute: typeof HowtoRoute
  RankingRoute: typeof RankingRoute
  SoloRoute: typeof SoloRoute
  WardrobeRoute: typeof WardrobeRoute
  DevGamePreviewRoute: typeof DevGamePreviewRoute
  DevUiPreviewRoute: typeof DevUiPreviewRoute
  MultiLocalRoute: typeof MultiLocalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wardrobe': {
      id: '/wardrobe'
      path: '/wardrobe'
      fullPath: '/wardrobe'
      preLoaderRoute: typeof WardrobeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solo': {
      id: '/solo'
      path: '/solo'
      fullPath: '/solo'
      preLoaderRoute: typeof SoloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/howto': {
      id: '/howto'
      path: '/howto'
      fullPath: '/howto'
      preLoaderRoute: typeof HowtoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multi/local': {
      id: '/multi/local'
      path: '/multi/local'
      fullPath: '/multi/local'
      preLoaderRoute: typeof MultiLocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/ui-preview': {
      id: '/dev/ui-preview'
      path: '/dev/ui-preview'
      fullPath: '/dev/ui-preview'
      preLoaderRoute: typeof DevUiPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/game-preview': {
      id: '/dev/game-preview'
      path: '/dev/game-preview'
      fullPath: '/dev/game-preview'
      preLoaderRoute: typeof DevGamePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HowtoRoute: HowtoRoute,
  RankingRoute: RankingRoute,
  SoloRoute: SoloRoute,
  WardrobeRoute: WardrobeRoute,
  DevGamePreviewRoute: DevGamePreviewRoute,
  DevUiPreviewRoute: DevUiPreviewRoute,
  MultiLocalRoute: MultiLocalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
